### ISSUE TITLE
Do yo need a Tesla?

### ISSUE THREAD

**Issue by pergolafabio** [pccr10001/TeslaWearKey#5]
Just wondering if this app can also be used for other purposes? Like to pair with an NFC tag/fob, for open door purposes?

Or is this wearapp, actually sending some unlock to the tesla app on android, that unlocks the car?

Thnx for feedback

**Comment by pccr10001** [comment]
Hi.

To use watch as NFC tag is based on your watch hardware, for my Galaxy Watch 4, the UID of watch is randomize, so I can't use my watch as NFC tag to unlock the door.
Maybe you can try NFC TagInfo app in Play Store to check your watch is randomize UID or not.

**Comment by pergolafabio** [comment]
I have the watch 5 pro, but i tought its the NFC card on the wearos, thats sends static or dynamic? its up to the app how its been developed?

**Comment by pccr10001** [comment]
Tesla Key Card is a card with Java engine called JavaCard, this project emulates TKC in WearOS to unlock car like original TKC, most of door lock to read card's UID using Mifare standard, so the UID is the one of factor that door lock understands, Tesla car doesn't care UID data, they only use ISO14443 protocol to communicate with program in the card.

**Comment by pergolafabio** [comment]
ok, then probably the app will not work on other terminals? :-)

**Comment by pccr10001** [comment]
yes, this app only works on Tesla cars
