### ISSUE TITLE
Couldn't install on Huawei watch 4 pro

### ISSUE THREAD

**Issue by vaminakov** [pccr10001/TeslaWearKey#7]
I'm trying to install latest version on Huawei watch 4 pro (latest harmony os 4):
```
.\adb.exe install 19.apk
Failed to install 19.apk: Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Reconciliation failed...: Reconcile failed: Package li.power.app.wearos.teslanak requires unavailable shared library com.google.android.wearable; failing!]
```
How possible to fix it?

**Comment by pccr10001** [comment]
This app is built on Google WearOS, maybe Huawei Watches are missing Google library to make this app worked.
Maybe you can build it by Huawei SDK, I have no Huawei Watch to test it.
