### ISSUE TITLE
Mainland China version of Samsung Watch 6 conflicts with Samsung smart card APP...

### ISSUE THREAD

**Issue by cdyui** [pccr10001/TeslaWearKey#8]
Tesla Wear Key works, but once I touch the Tesla, the NFC access card key pops up automatically. And the Samsung smart card APP cannot set Tesla Wear Key as the default NFC app...

Once I bring my watch close to the NFC reader, the access card or credit card will be opened by default, and Tesla Wear Key will be in the background and cannot be read.

**Comment by pccr10001** [comment]
Hi, do you have screenshot about NFC access card key app?
And also tell me the version of your watch OS version?

**Comment by cdyui** [comment]
你好。我的是中国大陆三星Watch 6手表机型。SoftWare Version:R9450ZCU1AXC2，Wear OS：4.0
中国大陆的手表有“三星智能卡”这个APP。这个APP可以使用小区门禁卡和公交卡。只要手表接触到NFC读卡器，就会默认打开“三星智能卡”，并且手表没有选项可以关闭默认打开。默认打开后会将TeslaWearKey至于后台，导致读取到的是门禁卡。

**Comment by cdyui** [comment]
> Hi, do you have screenshot about NFC access card key app? And also tell me the version of your watch OS version?

你好。我的是中国大陆三星Watch 6手表机型。SoftWare Version:R9450ZCU1AXC2，Wear OS：4.0
中国大陆的手表有“三星智能卡”这个APP。这个APP可以使用小区门禁卡和公交卡。只要手表接触到NFC读卡器，就会默认打开“三星智能卡”，并且手表没有选项可以关闭默认打开。默认打开后会将TeslaWearKey至于后台，导致读取到的是门禁卡。

只有我撤销门禁卡和公交卡，TeslaWearKey才会有效。但这样我无法使用门禁卡开门。这应该是三星的问题，如果三星可以提供一个选项：接触NFC读卡器设置哪个程序打开 就可以解决这个问题
![photo_2024-09-07_22-26-02](https://github.com/user-attachments/assets/3e229ab6-d51f-4c06-8c57-ce5e0ac08c21)
